In [1]:
# I confirm that I did not use ChatGPT or codes from the web or from past years’ assignments and that the work I submit is my own and my own only

In [2]:
#1.1    
def computeInverse(A):
    L, U = cs111.LUfactorNoPiv(A)
    (a_vec,b_vec) = np.shape(A)
    C = np.identity(a_vec)
    inv_A = C
    for i in range(0,a_vec):
        d = cs111.Lsolve(L, C[:, i])
        e = cs111.Usolve(U, d)
        inv_A[:, i] = e
    
    return inv_A

In [3]:
#1.2
import numpy as np
import numpy.linalg as npla
import cs111

A = np.array([[1,4,5],[4,17,26],[3,18,30]])
inv_A_1 = computeInverse(A)
inv_A_2 = npla.inv( A )
print("Inverse Calculation Using My Function:")
print(inv_A_1)

print("\nInverse Calculation Using Built-in Numpy Function")
print(inv_A_2)

print("\nDifference Between The Two:")
print(inv_A_1 - inv_A_2)

Inverse Calculation Using My Function:
[[-2.          1.42857143 -0.9047619 ]
 [ 2.         -0.71428571  0.28571429]
 [-1.          0.28571429 -0.04761905]]

Inverse Calculation Using Built-in Numpy Function
[[-2.          1.42857143 -0.9047619 ]
 [ 2.         -0.71428571  0.28571429]
 [-1.          0.28571429 -0.04761905]]

Difference Between The Two:
[[0.00000000e+00 2.22044605e-16 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]]
